cuda_model:
  device: cuda
  model_id: Qwen/Qwen2-7B-Instruct
  n_train: 10000
  n_eval: 500
  use_4bit: True
  device_map: auto



cpu_model:
  device: cpu
  model_id: Qwen/Qwen2-0.5B-Instruct
  n_train: 1000
  n_eval: 200
  use_4bit: False
  device_map: null